### ISSUE TITLE
Issue: After using the GPHUDClient.reboot function additional scripts won't work due to character not being online.

### ISSUE THREAD

**Issue by dazedwolf** [CoagulateSL/GPHUD#167]
**Describe the bug**
After using the GPHUDClient.reboot function additional scripts won't work due to the current character not being online until that character is selected manually via the switch character menu.

**To Reproduce**
1. Use a menu item that triggers the GPHUDClient.reboot.
2. HUD Reboots.
3. Use any script that requires the character to be online to run.
4. Recieve a generic script error that starts with: GPHUD: Script error: {GSResourceUnavailableException} Character Tiberius Ergos is not online at

Note: After switching back to the same character, or leaving and rejoining the instance the script works again. This doesn't happen 100% of the time but is highly reproducible. 

**Expected behavior**
Use the GPHUDClient.reboot function and have the character be online afterwords.

**Error Message**
GPHUD: Script error: {GSResourceUnavailableException} Character Tiberius Ergos is not online at 

**Additional context**
The feature is amazing and working super well, except for this scenario.

**Comment by dazedwolf** [comment]
After we've done some testing on this issue, we can confirm that it's a very high-frequency bug.

**Comment by dazedwolf** [comment]
Update: We've noticed this issue is still occurring. A common trait among the characters that are experiencing it is that they still contain unspent experience points. 

Performing multiple HUD Reboots usually resolves the issue.

**Comment by iprice** [comment]
For some reason I decided to make it a warm reboot (script shuts down and restarts) rather than just a hard llResetScript as per what /1reboot does.

I've a haunting feeling there's a reason for this but I've staged a change that just switches it to a hard reboot, though I'll probably do some work on figuring out why the soft reboot messes up since hard rebooting makes an unnecessary mess of the UI and maybe other things.

**Comment by iprice** [comment]
Root cause is the hud running disconnect() then setup() instantly after.

Order of requests reaching the server isn't guaranteed resulting in a race condition where a disconnect may process during/after the reconnection and break the connection, particularly since the client URL is reused.  Still, even with varied client URLs there's still a time of check to time of use race condition on disconnect.

So the soft solution that isn't a reset script is to make the soft reboot wait for disconnection to complete before it sets up a new connection, indicated by a "Disconnected, reconnecting..." message which is the server's completion of the disconnection, and the HUD then invokes the setup routine without fear of race condition.
