### ISSUE TITLE
GPHUDClient.offerWebsite

### ISSUE THREAD

**Issue by KimikoMazoku** [CoagulateSL/GPHUD#185]
**Describe the bug**
I am having difficulty getting an API command to operate from scripts, specifically offering a custom website. While this can be created as an Alias and assigned to menu buttons and will work, I can't seem to trigger it from within a script though it's listed as accessible from the scripting module. 

**To Reproduce**
The scripting line:
Integer discard=gsAPIX(CALLER,"GPHUDClient.offerWebsite",["URL here","Description here"]);

**Expected behavior**
In theory this should open the dialog with the URL offer. This line of script seems to satisfy all the arguments for the API called, However nothing happens. The APIX does not return any error, but nothing occurs either and no dialog box is opened or website offer made. 

**Error Message**
No error message generated

**Additional context**
I have also tried creating an Alias with the URL, that works when assigned as a menu button, but not when called from within a script. It produces a result similar to the above where seemingly all arguments are met, no error is returned, but nothing happens.
I'm not sure if I'm just missing something obvious or what!

**Comment by iprice** [comment]
Are you actually using that literal line above?  If so this would be sent to the script, and the appropriate LSL call invoked

https://wiki.secondlife.com/wiki/LlLoadURL

Which seems like it would silently ignore any URL not starting with http:// or https://

Try putting a real URL in there (even if its just google or youtube or whatever)

**Comment by KimikoMazoku** [comment]
I am not using the literal line above with "URL Here" in it,no. But using the above line with a website url doesn't produce a result for me. 

Integer discard=gsAPIX(CALLER,"GPHUDClient.offerWebsite",["https://www.wikipedia.org","Test Description"]);

Results in neither an APIX error or any seen effect, such as the offering of the website dialog. I have also tried putting URLs in both list space, just in case it.

**Comment by dazedwolf** [comment]
We had a similar issue and had to use an alias instead of a script to offer URLs.

**Comment by iprice** [comment]
Ah, yeah, that's never going to work, due to how responses and gsAPI work.

Specifically the API was mostly designed for the HUD to call, and offer website just sets up the response to open a webpage, that response normally goes to the HUD and everything works, but when called from scripting, it goes back to the script and you squash it down into the number 0 for success and all is lost.

I'm going to mark GPHUDClient.offerWebsite as not available to scripting, or the console, since it just won't function as intended in these calling paths.

Instead, since I rather not open raw HUD pushing of responses to a script, I'll add gsOfferWebsite that just takes the offerWebsite response and pushes it from HUD to server rather than using the normal (eaten by script) response channel.

**Comment by iprice** [comment]
Once I've rolled the update something like this should work fine

```
Integer online=gsOfferWebsite(CALLER,"https://www.wikipedia.org","Test Description");
gsSayToChar(CALLER,"Response code "+online);
```
