### ISSUE TITLE
Bug Report - New Reports not generating in HUD Website

### ISSUE THREAD

**Issue by dazedwolf** [CoagulateSL/GPHUD#194]
**Describe the bug**
No new reports are being generated in the GP HUD website, even though I have more than enough reporting credits.

**To Reproduce**
1. Log into GP HUD's website.
2. Go to the Report Page (https://sl.coagulate.net/GPHUD/reporting). 
3. Click on Generate New Report.
4. Get a message saying the report will be complete in approximately 1m 50s.
5. Wait for different amount of times (5 minutes, over an hour, multiple days)
6. No new report is generated. 

**Expected behavior**
For a new report to be available for download within a reasonable amount of time (5-10 minutes).

**Error Message**
None.

**Additional context**
We cannot verify potential rule breaks due to the inability to pull full reports.

**Comment by iprice** [comment]
Turns out two of your users have some weird group configuration which causes an exception when trying to work out "which single group of this attribute's group type are they in" due to it returning multiple results.

These users have EXCEPTION now printed in the broken cell, and the report otherwise logs and discards the exception, moving on to the next attribute.

Solved by #199
