### ISSUE TITLE
A function similar to llListFindList

### ISSUE THREAD

**Issue by ronlaws86** [CoagulateSL/GPHUD#280]
**Is your feature request related to a problem? Please describe.**
At present, there's no function to quick find the occurrence of an input in a list (Only a set)

**Describe the solution you'd like**
a function similar to llListFindList 
example: gsListFindList([input list], "search case")
Returns List index Integer value
-1 if not found 
0 - x as index position of match in list

Use cases: 
if (gsListFindList([input list], "search case") > -1) {
 // It is listed
} else {
// Not listed 
} 
can't think of any others off hand, but useful for retrieving data in all manner of ways
 
**Describe alternatives you've considered**
I have implimented this function in gsScript using a while loop and a counter to return an integer if it matches but large data sets will cause this to hit execution caps. 

**Additional context**
This is more a quality of life request for scripting, having  lists with no manipulation functions limits their usefulness.

**Comment by iprice** [comment]
I really should have gotten around to this sooner ; operations like this are quite inefficient to step through a list inside the scripting language (I guess it still runs fairly fast but there's a lot of unnecessary translation of code for something so core).

Kind of why there's an instruction count limit, to try push away from stuff that should be done 'natively' rather than implemented as a script its self.  But then that's on me to provide the functions really...
