### ISSUE TITLE
"OnNewCharacter" Script

### ISSUE THREAD

**Issue by justcfx2u** [CoagulateSL/GPHUD#30]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instance.CharInitScript runs on Characters.select.
Request for something that runs on Characters.create maybe here: https://github.com/CoagulateSL/GPHUD/blob/58794101218122ac3399610fe6c6885ead3e0180/src/net/coagulate/GPHUD/Modules/Characters/Login.java#L72 or here https://github.com/CoagulateSL/GPHUD/blob/58794101218122ac3399610fe6c6885ead3e0180/src/net/coagulate/GPHUD/Modules/Characters/Login.java#L79 ?

Some sort of hook that to allow a script a chance to manipulate the character according to current game rules on creation.

**Describe alternatives you've considered**
None

**Comment by iprice** [comment]
Any reason not to just switch to the new character and configure it using the normal Instance.RunOnLogin / Instance.CharInitScript features?  Specifically editing some one other than yourself is pretty awkward given CALLER wont be useful (as you wont be logged in as that character) and you'll fail every permissions check (because you're not logged in as that character) currently.

**Comment by justcfx2u** [comment]
That's a completely fair point. The real request is trying to figure out if a character is new or not, regardless of the method.
Sounds like a job for a custom flag.
