### ISSUE TITLE
Provide a function to read an experience value

### ISSUE THREAD

**Issue by KaiStaryk** [CoagulateSL/GPHUD#312]
**Describe the solution you'd like**
Optimally, two gs functions: one to set experience (and other) pools, and one to get the current experience (as an integer).

What I'd like to be able to do is allow characters to buy "cards" (which is just a KV integer) with experience.

Spoke to Iain about this 10/25/2024. He seemed to think it would be easy to implement.

**Comment by iprice** [comment]
We discussed 'get experience', there will be no 'set experience' beyond awarding xp to people.  The system does not properly support experience being modified negatively and I've told people not to use experience as a currency before, not sure why people dont just use currency for that since thats what that is for.

I'll provide a "get experience value", there is no "set value" on pools, only adjust value.  You can make it negative if you like, I think its a bad idea due to how ability points interact with XP, but i guess it will probably work, certainly not in any way I particularly support or intended.

So I'll give you the get XP.  You should be able to use the existing functions to modify XP though it may just outright reject -ve changes since it was designed to only go up.

**Comment by KaiStaryk** [comment]
Thank you!
