### ISSUE TITLE
New Function - GPHUDClient.RebootHUD

### ISSUE THREAD

**Issue by dazedwolf** [CoagulateSL/GPHUD#59]
**Is your feature request related to a problem? Please describe.**
Somewhat. There are instances where the HUD or Titler don't display accurate information (Debuff Icons not showing even after a texrefresh, titler values not updating, etc.). This would allow the user a 'manual reset' without looking for a HUDDeploy node to force it to update.

**Describe the solution you'd like**
This feature would be used to send the instance server a request for a new HUD/Titler for the avatar that used the command.
Reasoning: There are certain instances where the HUD's Titler or the HUD itself doesn't display accurate information, debuffs might not be showing up, old values might be stuck, etc. The current fix is to find a nearby HUD deploy node and use it. Having it as a menu option would give the users a faster on-the-fly troubleshooting option. 

**Describe alternatives you've considered**
We currently have several objects across the sim that users can use to get a new hud attached to them. 

**Additional context**
This is not urgent, just a nice quality of life update. 

**Edit: Please ignore the above. A menu-configurable option to reboot the HUD would work dramatically better. I'll also focus on tracking and posting bugs that would make the user need to use such a feature.**

**Comment by iprice** [comment]
Hi.

Firstly, please open a secondary issue for the things that aren't updating ; *ideally* if you can find a consistent way to reproduce the problem then thats something I can actively sit down for a few hours and work on debugging to see whats going on, otherwise an issue to track sightings and any insight will give a place to focus a longer term fix for this.

A new HUD shouldn't be necessary, as a lousy work around you should be able to issue /1reboot which will cause the HUD to reset its internal state and initiate a new login, as part of a new login the server side 'cache' of values the HUD knows about is also purged to ensure the HUD gets a full state dump from the server, and is effectively the same as getting a new HUD (it's technically possible for a bug to exist that would cause update issues to persist from hud to hud, though thats very unlikely given this wiping that happens at login).

https://github.com/CoagulateSL/GPHUD/blob/master/LSL/HUD.lsl#L333

Let me know if that does the job for you, and if so perhaps what you want is an ability to bind a "reboot me" command to a menu somewhere, which I guess I can invoke from the server without requiring a new HUD to be deployed by using this old general purpose hook

**Comment by dazedwolf** [comment]
Hello Iain,

There are a few random cases where it can have some issues, I'll definitely post bugs when I narrow them down. I know of one related to effects and I can test reproducing it for a bit today before posting the issue. 

I agree with you. Having the reboot option would 100% be better and fully encompass what I'm needing. I'll go ahead and edit the title from GPHUDClient.GetHUD to GPHUDClient.RebootHUD since the goal is to have a menu button that the user can use to reboot the HUD.

Thanks!
