### ISSUE TITLE
Feature Request - Ability to suppress message to target on administrative group join/leave commands

### ISSUE THREAD

**Issue by dazedwolf** [CoagulateSL/GPHUD#73]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
A gsElavatedAPI that will cause the called API to not post a message in chat. 
Ex.: using gsElavatedAPIS to call the groups.add command to add someone to a group but not having it post in the chat they were added to said group.

**Describe alternatives you've considered**
Possibly having a 'silent' group add option would also work. However, I haven't found that option.

**Additional context**
We use a lot of groups to manage certain HUD settings, classes, features, etc. We would like to not have it post a message in some cases when people's groups are changed. Adding a gsElavatedAPI that would cause every API called to not post would resolve our issue and possibly add the option for other silent commands to give the user a cleaner experience.

Note: If this is a lot of work, just having the option to add someone to a group with a command without it posting in chat would be wonderful! 

Thanks!

**Comment by ronlaws86** [comment]
API.java
```
@Nonnull
	@GSFunctions.GSFunction(description="Calls a standard GPHUD API command with full permissions, throwing a script error if the API call fails",
	                        parameters="Character caller - User invoking the API<br>String apicall - "+"name of API command "+"to"+" call<br>BCList parameters - list of "+"STRING parameters to the target API",
	                        returns="A Response",
	                        notes="",
	                        privileged=true,
	                        category= SCRIPT_CATEGORY.API)
	public static BCResponse gsElevatedAPIS(final State st,
	                                        @Nonnull final GSVM vm,
	                                        @Nonnull final BCCharacter caller,
	                                        @Nonnull final BCString apicall,
	                                        @Nonnull final BCList parameters) {
		final BCResponse response=gsAPI(st,vm,caller,apicall,parameters,true);
		if (response.isError()) { throw new UserInputStateException(response.toBCString().getContent(),true); }
		return;
	}
```
@iprice I know it's jank but would something like this work? just return empty instead of returning response

**Comment by iprice** [comment]
This probably won't work - the Response object from "API calls" is the response that normally goes back to the calling user, bearing in mind that Groups.Add is /intended/ as an administrative function for joining some other player to a group.

https://github.com/CoagulateSL/GPHUD/blob/master/src/net/coagulate/GPHUD/Modules/Groups/Management.java#L297

Specifically the "response" contains something like "<name> is now in group <name>" or "<name> was moved into group <name> (was formerly <name>)" as can be seen by the setting of "result" in this method, eventually returned in a new OKResponse.  For API calls made by script, this response is basically passed the "GSVM" (thing that runs scripts) and pushed onto the stack, which then probably gets pulled off during the assignment to a variable ; if you pull the string form of that response you'll get the above messages, but those above messages don't progress to the user when done by scripting already unless you specifically forward them.

Likely the issue lies with the events of line 327
https://github.com/CoagulateSL/GPHUD/blob/master/src/net/coagulate/GPHUD/Modules/Groups/Management.java#L327
which explicitly calls the target's hudMessage to inform them of the changes to their character made by a remote administrator.

Likely best solution here is to add an optional argument to the method for suppressing the notification, default it to false if its not set, and then block that line of code if it is set.  Overall about as much work as writing this comment I suppose ;)

**Comment by iprice** [comment]
Less relevantly but of note - that won't compile as the method is declared as returning a BCResponse, so return with nothing after it will be an error ; you could 'return null' but this would likely crash the scripting engine when it tried to dump that onto stack ; also the @Nonnull annotation prohibits a null return value (because the calling GSVM code can't handle that, scripting doesn't have null support in it overall).  Closest would be an NoResponse from the selection in https://github.com/CoagulateSL/GPHUD/tree/master/src/net/coagulate/GPHUD/Interfaces/Responses
